import = ["~/.config/alacritty/catppuccin-mocha.toml"]
live_config_reload = true
[font.normal]
family = "JetBrainsMonoNF"
style = "Regular"

[shell]
# TMUX
program = "tmux"
args = ["new-session", "-A", "-s", "main"]
# Zellij
# program = "zellij"
# args = ["--session", "main"]

[window]
decorations = "None"
dynamic_padding = true
