[font.normal]
family = "JetBrainsMono"
style = "Regular"

# [shell]
# program = "tmux"
# args = ["new-session", "-A", "-s", "main"]
# program = "zellij"
# args = ["--session", "main"]

[window]
decorations = "None"
dynamic_padding = true

[general]
live_config_reload = true
import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[terminal]
