import = ["~/.config/alacritty/tokyonight-moon.toml"]
live_config_reload = true
[font.normal]
family = "JetBrainsMonoNF"
style = "Regular"

[shell]
args = ["new-session", "-A", "-s", "main"]
program = "tmux"

[window]
decorations = "None"
dynamic_padding = true
