alias vim=nvim
alias ls=eza
alias ll='ls -l'
alias la='ls -lA'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias lg=lazygit
alias bc=bin/console
alias bac=bin/adminconsole
alias bwc=bin/websiteconsole
alias dbx=devbox
alias gsw='git switch'
alias cat=bat
alias less=moar
