alias ls=lsd
alias ll='ls -lh'
alias la='ls -lAh'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias lg=lazygit
alias bc=bin/console
alias bac=bin/adminconsole
alias bwc=bin/websiteconsole
alias dbx=devbox
alias gsw='git switch'
alias cat=bat
alias less=moar
