# basic zsh conf
export ZSH_HOME=$HOME/.config/zsh
## History
HISTFILE=$HOME/.history
HISTSIZE=50000
SAVEHIST=50000
HISTDUP=erase
setopt appendhistory
setopt sharehistory
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_ignore_dups
setopt hist_find_no_dups
export EDITOR=nvim
# export VISUAL=nvim

bindkey -e

# load aliases & functions
source ${ZSH_HOME}/aliases.zsh
source ${ZSH_HOME}/functions.zsh

if [[ -f "/opt/homebrew/bin/brew" ]] then
  # If you're using macOS, you'll want this enabled
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

# gpg-agent config (yubikey as ssh key)
# export GPG_TTY="$(tty)"
# export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
# gpgconf --launch gpg-agent

# pre plugin load configs
export NVM_LAZY_LOAD=true
# export NVM_AUTO_USE=true # automatically run `nvm use` when entering a dir with a nvmrc. doesn't work with lazy loading

# load plugins with antidote
# source '/usr/share/zsh-antidote/antidote.zsh' # antidote installed from AUR
# source ~/.nix-profile/share/antidote/antidote.zsh # antidote installed from NIX
source $HOMEBREW_PREFIX/opt/antidote/share/antidote/antidote.zsh # antidote installed with brew
antidote load ${ZSH_HOME}/zsh_plugins.txt

# post plugin load configs
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# load more stuff
## load oh-my-posh
eval "$(oh-my-posh init zsh --config $ZSH_HOME/omp.toml)"

## direnv
export DIRENV_LOG_FORMAT=''
eval "$(direnv hook zsh)"

## zoxide (better zsh-z)
eval "$(zoxide init --cmd cd zsh)"

## fzf
source <(fzf --zsh)

# autocompletion
autoload -U compinit; compinit

## styling
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*' menu no
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'ls --color $realpath'
zstyle ':fzf-tab:complete:__zoxide_z:*' fzf-preview 'ls --color $realpath'

export PATH="$PATH:/nix/var/nix/profiles/default/bin"

if [ -e /home/patrick/.nix-profile/etc/profile.d/nix.sh ]; then . /home/patrick/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer

# Created by `pipx` on 2025-03-12 19:07:03
export PATH="$PATH:/Users/patrick/.local/bin"

# bun completions
[ -s "/Users/patrick/.bun/_bun" ] && source "/Users/patrick/.bun/_bun"

# jj completions
source <(jj util completion zsh)

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
