# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# basic zsh conf
export ZSH_HOME=$HOME/.config/zsh
export HISTFILE=$HOME/.history
export HISTSIZE=1000
export SAVEHIST=1000
export EDITOR=nvim
setopt sharehistory

# load aliases & functions
source ${ZSH_HOME}/aliases.zsh
source ${ZSH_HOME}/functions.zsh

# gpg-agent config (yubikey as ssh key)
export GPG_TTY="$(tty)"
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
gpgconf --launch gpg-agent

# pre plugin load configs
export NVM_LAZY_LOAD=true
# export NVM_AUTO_USE=true # automatically run `nvm use` when entering a dir with a nvmrc. doesn't work with lazy loading

# load plugins with antidote
# source '/usr/share/zsh-antidote/antidote.zsh' # antidote installed from AUR
source ~/.nix-profile/share/antidote/antidote.zsh # antidote installed from NIX
antidote load ${ZSH_HOME}/zsh_plugins.txt

# post plugin load configs
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# load more stuff
## load p10k
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

## direnv
export DIRENV_LOG_FORMAT=''
eval "$(direnv hook zsh)"

## zoxide (better zsh-z)
eval "$(zoxide init --cmd cd zsh)"
